M3T:
  device_name: DJI_M3T
  cameras:
    EO:
      camera_name: DJI-M3T-eo
      sensor_type: EO
      photo_resolutions:
      - - 4000
        - 3000
      - - 8000
        - 6000
      video_resolutions:
      - - 1920
        - 1080
      - - 3840
        - 2160
      photo_extensions: [".JPG", ".JPEG"]
      video_extensions: [".MP4"]
      intrinsic_settings:
        distortion_coefficients:
        # - 2.41e-01
        # - -6.90e-01
        # - 8.63e-04
        # - -9.16e-04
        # - 5.40e-01
        - [0.24186862, -0.69030567, 0.00086349, -0.00091624, 0.5400296]
        image_size:
        - 1920
        - 1080
        K_coefs:
        - 1.38726502e+03
        - 1.38764439e+03
        - 9.56787476e+02
        - 5.37653682e+02
    IR:
      camera_name: DJI-M3T-ir
      sensor_type: lwir
      photo_resolutions:
      - - 640
        - 512
      video_resolutions:
      - - 640
        - 512
      photo_extensions: [".JPG", ".JPEG"]
      video_extensions: [".MP4"]
      intrinsic_settings:
        distortion_coefficients:
        - [-3.66193110e-01, 3.22822375e-02, 9.26470838e-04, -7.95239718e-05, 2.08960779e-01]
        # - -3.66e-01
        # - 3.23e-02
        # - 9.26e-04
        # - -7.95e-05
        # - 2.09e-01
        image_size:
        - 640
        - 512
        K_coefs:
        - 765.57381651
        - 767.15530219
        - 314.21786392
        - 240.58687479
  homographies:
    EO_IR:
      # - [5.54e-01, -1.16e-02, -2.02e+02]
      # - [-1.03e-03, 5.47e-01, -4.13e+01]
      # - [5.75e-06, -2.51e-05, 1.0e+00]
      # - [5.52452014e-01, -3.06957075e-03, -2.02065560e+02]
      # - [8.10475597e-04, 5.49910326e-01, -4.28903140e+01]
      # - [2.47186678e-06, -1.17449185e-05, 1.00000000e+00]
      - [5.51515158e-01, -1.63266364e-04, -2.03635071e+02]
      - [-2.42275586e-03, 5.49896744e-01, -4.10670068e+01]
      - [-4.21572491e-06, -6.26932487e-06, 1.00000000e+00]
  regex: ^.*_(\d+)\.[a-zA-Z0-9]+$